web:
  port: 8080
cors:
  allowedOrigins:
    - http://localhost:3000
https:
  key: ./key.pem
  certificate: ./certificate.pem
mongoDb:
  clusterURI: mongodb+srv://adminuser:<<pass>>@cluster0.3h1po.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
  database: bookdeno